// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfMdHP4RPnxtfHVYTdvaUKZ3HTWb3ACHU',
    appId: '1:686525289113:web:03b06b50df43905ed89e08',
    messagingSenderId: '686525289113',
    projectId: 'audiomusic-ebba6',
    authDomain: 'audiomusic-ebba6.firebaseapp.com',
    storageBucket: 'audiomusic-ebba6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsbWNPQQLLzXTsMJPcf9wvyrFRAorre0E',
    appId: '1:686525289113:android:929a20e9b2108841d89e08',
    messagingSenderId: '686525289113',
    projectId: 'audiomusic-ebba6',
    storageBucket: 'audiomusic-ebba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFAnpkQNaK61AbZQGLG6TdES3Hd_-Y7cY',
    appId: '1:686525289113:ios:e7796e3d0ae9e019d89e08',
    messagingSenderId: '686525289113',
    projectId: 'audiomusic-ebba6',
    storageBucket: 'audiomusic-ebba6.appspot.com',
    iosBundleId: 'com.example.audioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFAnpkQNaK61AbZQGLG6TdES3Hd_-Y7cY',
    appId: '1:686525289113:ios:e7796e3d0ae9e019d89e08',
    messagingSenderId: '686525289113',
    projectId: 'audiomusic-ebba6',
    storageBucket: 'audiomusic-ebba6.appspot.com',
    iosBundleId: 'com.example.audioapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfMdHP4RPnxtfHVYTdvaUKZ3HTWb3ACHU',
    appId: '1:686525289113:web:a98062832aa4a270d89e08',
    messagingSenderId: '686525289113',
    projectId: 'audiomusic-ebba6',
    authDomain: 'audiomusic-ebba6.firebaseapp.com',
    storageBucket: 'audiomusic-ebba6.appspot.com',
  );

}